development:
  adapter: postgresql
  encoding: unicode
  database: job_app
  pool: 5
  username: severnsc
  password: ENV['DB_PASSWORD']

test:
  adapter: postgresql
  encoding: unicode
  database: job_app_test
  pool: 5
  username: severnsc
  password: ENV['DB_PASSWORD']